export const data = [
    { index: 0, heading: "Nikhil" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
    { index: 1, heading: "Tripti" },
  ];
